# Generated by Django 5.2 on 2025-05-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'administrateur'), (1, 'promoteur'), (2, 'prefet'), (3, 'directeur'), (4, 'comptable'), (5, 'secretaire'), (6, 'enseignant'), (7, 'eleve')], default=7),
        ),
    ]
