# Generated by Django 5.2 on 2025-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom_pere', models.CharField(max_length=100)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('nom_mere', models.CharField(max_length=100)),
                ('telephone_pere', models.CharField(max_length=15, unique=True)),
                ('telephone_mere', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=100)),
                ('code_section', models.CharField(max_length=2, unique=True)),
            ],
        ),
    ]
